#ifndef INSTRUCTIONSET_H
#define INSTRUCTIONSET_H

QString instructionset[] = {"NOP", "LXI", "STAX", "INX", "INR", "DCR", "MVI", "RLC", "XTHL", "DAD", "LDAX", "DCX", "RRC", "PCHL", "RAL", "RAR", "SHLD", "DAA", "LHLD", "CMA", "STA", "STC", "LDA", "CMC", "MOV", "HLT", "ADD", "ADC", "SUB", "SBB", "ANA", "XRA", "ORA", "CMP", "RNZ", "POP", "JNZ", "JMP", "CNZ", "PUSH", "ADI", "RST", "RZ", "RET", "JZ", "CZ", "CALL", "ACI", "RNC", "JNC", "CNC", "SUI", "RC", "IN", "SBI", "RPO", "POP", "JPO", "CPO", "ANI", "RPE", "PCHL", "JPE", "XCHG", "CPE", "XRI", "RP", "JP", "CP", "ORI", "RM", "SPHL", "JM", "CM", "CPI"};

QString instructions = " NOP LXI STAX INX INR DCR MVI RLC XTHL DAD LDAX DCX RRC PCHL RAL RAR SHLD DAA LHLD CMA STA STC LDA CMC MOV HLT ADD ADC SUB SBB ANA XRA ORA CMP RNZ POP JNZ JMP CNZ PUSH ADI RST RZ RET JZ CZ CALL ACI RNC JNC CNC SUI RC IN SBI RPO POP JPO CPO ANI RPE PCHL JPE XCHG CPE XRI RP JP CP ORI RM SPHL JM CM CPI ";

#endif // INSTRUCTIONSET_H
